### PR TITLE
fix: rmdir is being deprecated

### PR DESCRIPTION
**Pull request by JuanRamirezC**
This PR fixes #
Since Yesterday Installing dependencies are failing, there is a warning about a deprecation happening 
Captura de Pantalla 2021-12-03 a la(s) 10 03 42 a m

### CODE REVIEW

**Comment by jasonxylee** [comment]
I'm running into the same issue, and when I run this action in my GitHub Actions pipeline, it does not install dependencies. 
And then it complains that it cannot find node_modules. 

```
2021-12-03T15:36:47.4098354Z HEAD is now at 6d2cb12 Merge d89f420e7bc8d9aa5f29e53e63bf0a7a33320743 into 2943fa653b297c73b6c08d4ada6049215c67a851
2021-12-03T15:36:47.4257492Z ##[group]Run ArtiomTr/jest-coverage-report-action@v2.0-rc.3
2021-12-03T15:36:47.4258098Z with:
2021-12-03T15:36:47.4259017Z   github-token: ***
2021-12-03T15:36:47.4259457Z   working-directory: ./ts
2021-12-03T15:36:47.4259953Z   test-script: npm run test:coverage-ci
2021-12-03T15:36:47.4260416Z   icons: emoji
2021-12-03T15:36:47.4260765Z   annotations: all
2021-12-03T15:36:47.4261185Z   package-manager: npm
2021-12-03T15:36:47.4261599Z   skip-step: none
2021-12-03T15:36:47.4261952Z ##[endgroup]
2021-12-03T15:36:47.4312017Z ##[group]Run $GITHUB_ACTION_PATH/run.sh
2021-12-03T15:36:47.4312543Z [36;1m$GITHUB_ACTION_PATH/run.sh[0m
2021-12-03T15:36:47.4353788Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2021-12-03T15:36:47.4354253Z env:
2021-12-03T15:36:47.4355265Z   INPUT_GITHUB-TOKEN: ***
2021-12-03T15:36:47.4355804Z   INPUT_TEST-SCRIPT: npm run test:coverage-ci
2021-12-03T15:36:47.4356398Z   INPUT_THRESHOLD: 
2021-12-03T15:36:47.4356846Z   INPUT_WORKING-DIRECTORY: ./ts
2021-12-03T15:36:47.4357289Z   INPUT_ICONS: emoji
2021-12-03T15:36:47.4357677Z   INPUT_ANNOTATIONS: all
2021-12-03T15:36:47.4358127Z   INPUT_PACKAGE-MANAGER: npm
2021-12-03T15:36:47.4358571Z   INPUT_SKIP-STEP: none
2021-12-03T15:36:47.4358947Z ##[endgroup]
2021-12-03T15:36:47.4936246Z Running using node v16.13.0
2021-12-03T15:36:47.6393748Z (node:1495) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
2021-12-03T15:36:47.6395866Z (Use `node --trace-deprecation ...` to show where the warning was created)
2021-12-03T15:36:47.6409584Z ##[error]ENOENT: no such file or directory, stat 'ts/node_modules'
2021-12-03T15:36:47.6453265Z ##[error]Process completed with exit code 1.
```

inside package.json:

```js
{
    "test:coverage": "jest --silent --ci --coverage --testLocationInResults --json --outputFile='report.json'",
    "test:coverage-ci": "npm install; npm run test:coverage",
}
```

**Comment by ArtiomTr** [comment]
Hey @JuanRamirezC :wave:,

Thank you for your work! Unfortunately, by replacing `rmdir` with `rm` will drop the support for node versions above `14.14.0`, because `rm` function was introduced only in that version ([docs](https://nodejs.org/docs/latest-v17.x/api/fs.html)).
I understand that this migration is necessary, but should be done more smoothly - it is better to check the node version to decide which function to call - `rm` or `rmdir`.
I would be glad if you could add support for older versions in your PR. Also update your tests as needed.

**Comment by ArtiomTr** [comment]
Hello @jasonxylee :wave:,

You're getting slightly different error - `rmdir` results in `ENOENT` exception. This could be possibly fixed by wrapping these lines of code into try / catch block: https://github.com/ArtiomTr/jest-coverage-report-action/blob/ad026e403e88f974d12e0184dcb5db7cf673d95e/src/stages/installDependencies.ts#L11-L14

But, as I mentioned before, this does not fit the topic of this PR. I will create a separate issue for your problem

**Comment by ArtiomTr** [comment]
Sorry, missclick 😄

**Pull request closed without merging**
