### PR TITLE
Load jest config from package.json if no dedicated config file found

### LINKED ISSUE #228: Parse threshold information from jest configuration in 'package.json'
### Idea

Action should parse threshold information not only from `jest.config.*` files, but also from `package.json`.

### Description

The schema of jest configuration in `package.json` file is described [here](https://jestjs.io/docs/configuration)

### Additional context

Originally described in #223 issue.

### PR DESCRIPTION
**Pull request by aj8k**
This PR fixes #228

Hi! Initially tried to fix the issue with help of updated version of `c12` library https://github.com/ArtiomTr/jest-coverage-report-action/pull/371, but it breaks build and makes PR too big. So here is a simplified version.

### CODE REVIEW

**Comment by aj8k** [comment]
@ArtiomTr I have a question if these thresholds have any effect at all? I could see that in https://github.com/ArtiomTr/jest-coverage-report-action/blob/main/src/stages/createReport.ts that the red/yellow/green circle should come from `formatCoverage` function. But it takes only one number as threshold, not 4 as in jest config. And actually it is `undefined` in all usages of this function. And looks like the indicators always shows status comparing with default 60% coverage. Do I miss something, as actually this PR should work, it actually work but doesn't change indicator statuses based on my thresholds.

**Comment by ArtiomTr** [comment]
Hey @aj8k :wave:,

No, currently thresholds do not affect the colours of those circles. However, thresholds are a necessary part of this action, as they validate your coverage and report errors.

Fixing the colours of those circles isn't a straightforward thing to do. The fix is planned for the `v3` version.

Thank you for your contribution!

**Comment by ArtiomTr** [comment]
@all-contributors please add @aj8k for code

**Comment by ArtiomTr** [comment]
The fix is now available under [v2.2.4](https://github.com/ArtiomTr/jest-coverage-report-action/releases/tag/v2.2.4) or just [v2](https://github.com/ArtiomTr/jest-coverage-report-action/releases/tag/v2) versions.

**Comment by aj8k** [comment]
Oh, I see. Thanks for quick response!

**Pull request merged**
