### PR TITLE
feat: added coverage annotations filters

### PR DESCRIPTION
**Pull request by xShteff**
Hi there @ArtiomTr, hope it's alright I open a PR here. 

We tried using your action and found it a bit loud. For five lines of code it managed to produce an equal amount of annotations. I've tried to pull out a way to filter out some of these, also updated some of your tests to match the new implementation. 

image

Let me know if I missed anything :)

### CODE REVIEW

**Comment by xShteff** [comment]
Actually I see the coverage for `Options.ts` went down - I'll look into it :)

**Comment by ArtiomTr** [comment]
Hello @xShteff,

Thank you for the contribution. Coverage in `Options.ts` isn't a big deal.

About your problem - I think it is better to have something like #147, than filtering coverage annotations - you can accidentally filter out important annotations.

**Comment by ArtiomTr** [comment]
> Perhaps at some point it could be worth looking into comments as well, but for now this would bring us a lot of value (:

Yeah, I understand that it is a good fix to reduce loudness. But my point is - maybe uncovered line annotations will suit your needs? I just don't want to add a new feature, that is likely to be deprecated once uncovered line annotations will land. I believe, that user expects to see which *lines* are not covered, not statements/branches/functions.

**Comment by xShteff** [comment]
> > Perhaps at some point it could be worth looking into comments as well, but for now this would bring us a lot of value (:
> 
> Yeah, I understand that it is a good fix to reduce loudness. But my point is - maybe uncovered line annotations will suit your needs? I just don't want to add a new feature, that is likely to be deprecated once uncovered line annotations will land. I believe, that user expects to see which _lines_ are not covered, not statements/branches/functions.

It is fair - in the end it's your repo and it's up to you if you want to introduce the feature or not :). In my mind this is not a enforced change but a possibility to make it more customisable to fit our specific use case.

Let me know if I should close the PR :)

**Pull request closed without merging**
