### PR TITLE
Refactor: fix typing for fetchPreviousReport.ts

### PR DESCRIPTION
**Pull request by MH4GF**
### What does this PR do?

A small fix to correctly guess the octokit response type and removed any.

### CODE REVIEW

**Review by ArtiomTr — APPROVED** [review]
Perfect 👍

**Comment by ArtiomTr** [comment]
@all-contributors please add MH4GF for code

**Comment by ArtiomTr** [comment]
@MH4GF thank you for the contribution!

**Comment by MH4GF** [comment]
@ArtiomTr Thanks for the quick response, too! 😸

**Pull request merged**
